"""create_job_table

Revision ID: 7fadcf250eca
Revises:
Create Date: 2025-04-10 23:23:56.553120

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7fadcf250eca"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("id", sa.Uuid(), nullable=False, comment="Идентификатор вакансии"),
        sa.Column(
            "user_id", sa.Uuid(), nullable=False, comment="Идентификатор пользователя"
        ),
        sa.Column("title", sa.String(), nullable=False, comment="Название вакансии"),
        sa.Column(
            "description", sa.String(), nullable=False, comment="Описание вакансии"
        ),
        sa.Column("salary_from", sa.Integer(), nullable=False, comment="Зарплата от"),
        sa.Column("salary_to", sa.Integer(), nullable=False, comment="Зарплата до"),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Флаг активности вакансии",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Дата публикации вакансии",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Пользователи",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job")
    # ### end Alembic commands ###
