"""create_response_table

Revision ID: bc0787573f84
Revises: 7fadcf250eca
Create Date: 2025-04-10 23:25:00.629141

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc0787573f84"
down_revision: Union[str, None] = "7fadcf250eca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "response",
        sa.Column("id", sa.Uuid(), nullable=False, comment="Идентификатор отклика"),
        sa.Column(
            "user_id", sa.Uuid(), nullable=False, comment="Идентификатор пользователя"
        ),
        sa.Column(
            "job_id", sa.Uuid(), nullable=False, comment="Идентификатор вакансии"
        ),
        sa.Column(
            "message", sa.String(), nullable=False, comment="Сопроводительное письмо"
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Отклики",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("response")
    # ### end Alembic commands ###
